"""
Optimal Union Finder - Find the best unions of elements using branch-and-bound algorithm.

This module implements a generator-based algorithm to find unions (combinations) of elements
that maximize a score function, where each union has a maximum size constraint.

It differs from the branch-and-bound algorithm in that sense
that it yields mutliple solution ordered by their score - the most optimal first.
This is done to give the user some options to choose from.
"""
from collections import defaultdict
from collections.abc import Iterable, Iterator
from functools import cached_property, total_ordering
from typing import Protocol, Self, cast, runtime_checkable

@total_ordering
@runtime_checkable
class ElementProtocol(Protocol):
    @cached_property
    def score(self) -> int:
        ...
    def __lt__(self, other: object) -> bool:
        ...
    def __eq__(self, other: object) -> bool:
        ...


@total_ordering
@runtime_checkable
class UnionProtocol[Element: ElementProtocol](Protocol):
    @cached_property
    def score(self) -> int:
        ...
    def is_compatible(self, element: Element) -> bool:
        ...
    def copy_and_expand_copy(self, element_to_expand_with: Element) -> Self:
        ...
    def __len__(self) -> int:
        ...
    def __lt__(self, other: object) -> bool:
        ...
    def __eq__(self, other: object) -> bool:
        ...


class FindOptimalUnionIterator[Element: ElementProtocol, Union]:
    """
    Branch-and-bound generator for optimal unions.
    
    Uses a best-first search strategy to yield unions in descending order of score.
    Only yields unions when their score is proven to be at least as good as any
    undiscovered union (based on the upper bound heuristic).
    """
    _unions_max_length: int
    _elements_generator: Iterator[Element]
    _unions: set[UnionProtocol[Element]]
    _unexpandable_unions: set[UnionProtocol[Element]]
    _unions_with_max_score_per_length: defaultdict[int, int]
    _future_unions_score_upper_bound: float

    def __init__(
            self,
            unions_max_length: int,
            root_union: UnionProtocol[Element],
            elements_descending_by_score: Iterable[Element]
        ):
        """Initialize the union generator.
        
        Args:
            elements_descending_by_score: Iterable of elements sorted by score (high to low).
            root_union: Initial union to start the search from.
            unions_max_length: Maximum number of elements allowed in any union.
        """
        self._unions_max_length = unions_max_length
        self._elements_generator = iter(elements_descending_by_score)
        self._unions = set()
        self._unexpandable_unions = set()
        self._unions_with_max_score_per_length = defaultdict(int)
        self._future_unions_score_upper_bound = float("inf")
        self._add_union(root_union)

    def __iter__(self) -> Iterator[Union]:
        return self

    def __next__(self) -> Union:
        """
        Yield the next best union.
        
        Returns:
            A union which is guaranteed to have a higher score
            than any future union generated by this instances.
            
        Raises:
            StopIteration: When all unions have been yielded.
        """
        for element in self._elements_generator:
            if yieldable_union := self._try_to_get_yieldable_union():
                return cast(Union, yieldable_union)
            for union in sorted(self._unions):
                if union.is_compatible(element):
                    self._add_union(union.copy_and_expand_copy(element))
            if len(self._unions_with_max_score_per_length) > 0:
                self._future_unions_score_upper_bound = max(
                    element.score * (self._unions_max_length - length) + score
                    for length, score in self._unions_with_max_score_per_length.items()
                )
        if len(self._unions) > 0:
            self._unexpandable_unions.update(self._unions)
            self._unions.clear()
            self._unions_with_max_score_per_length.clear()
            self._future_unions_score_upper_bound = 0
        if yieldable_union := self._try_to_get_yieldable_union():
            return cast(Union, yieldable_union)
        raise StopIteration

    def _add_union(self, new_union: UnionProtocol[Element]):
        if len(new_union) >= self._unions_max_length:
            self._unexpandable_unions.add(new_union)
        else:
            self._unions.add(new_union)
            if self._unions_with_max_score_per_length[len(new_union)] < new_union.score:
                self._unions_with_max_score_per_length[len(new_union)] = new_union.score

    def _try_to_get_yieldable_union(self) -> UnionProtocol[Element] | None:
        if len(self._unexpandable_unions) == 0:
            return None

        most_promising_union = max(self._unexpandable_unions)
        print(f"future_unions_score_upper_bound: {self._future_unions_score_upper_bound}")
        print(f"most_promising_union (score {most_promising_union.score}): {most_promising_union}")
        if most_promising_union.score >= self._future_unions_score_upper_bound:
            self._unexpandable_unions.remove(most_promising_union)
            return most_promising_union
